title: COVID-19 Tracker | INDIA
description: Coronavirus Outbreak in India: Latest statewise and datewise ACTIVE, CONFIRMED, RECOVERED cases in graphs and map
theme: jekyll-theme-minimal
logo: img/corona.gif
author: Vinit Shahdeo
plugins:
  - jemoji
