title: COVID-19 Tracker | INDIA
description: Coronavirus Outbreak in India: Latest statewise/datewise ACTIVE | CONFIRMED | RECOVERED cases in graphs and map
theme: jekyll-theme-minimal
logo: img/corona.gif
plugins:
  - jemoji
